name: FoodLog
options:
  bundleIdPrefix: com.tevon.foodlog
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
settings:
  SWIFT_VERSION: "5.9"
  TARGETED_DEVICE_FAMILY: "1"
targets:
  FoodLog:
    type: application
    platform: iOS
    sources:
      - FoodLog
      - Shared
    resources:
      - path: FoodLog/Resources
        buildPhase: resources
    settings:
      INFOPLIST_FILE: FoodLog/Info.plist
      CODE_SIGN_ENTITLEMENTS: FoodLog.entitlements
      PRODUCT_BUNDLE_IDENTIFIER: com.tevon.foodlog
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: "1"
      DEVELOPMENT_TEAM: "C8579683ZP"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - sdk: libsqlite3.tbd
      - target: NutrientsWidget

  NutrientsWidget:
    type: app-extension
    platform: iOS
    sources:
      - NutrientsWidget
      - Shared
    settings:
      INFOPLIST_FILE: NutrientsWidget/Info.plist
      CODE_SIGN_ENTITLEMENTS: NutrientsWidget/NutrientsWidget.entitlements
      PRODUCT_BUNDLE_IDENTIFIER: com.tevon.foodlog.NutrientsWidget
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: "1"
      DEVELOPMENT_TEAM: "C8579683ZP"
